---
on:
  pull_request: {}
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3.3.0"
      - uses: "actions/setup-go@v4"
        with:
          cache: true
      - run: "go build ./..."

  generate:
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3.3.0"
      - uses: "actions/setup-go@v4"
        with:
          cache: true

      - run: "go generate unifi/device.go"
      - run: "git diff --compact-summary --exit-code"

  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3.3.0"
      - uses: "actions/setup-go@v4"
        with:
          cache: true
      - uses: "golangci/golangci-lint-action@v3"
        with:
          skip-pkg-cache: true

  test:
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3.3.0"
      - uses: "actions/setup-go@v4"
        with:
          cache: true
      - run: "go test ./..."
