---
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  fields:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/setup-go@v3"
        with:
          go-version-file: "go.mod"
          cache: true

      - uses: "actions/checkout@v3.3.0"

      # TODO: Automatically merge the PR if tests pass.
      - run: "go generate unifi/fields.go"
      - uses: "peter-evans/create-pull-request@v4"
        with:
          delete-branch: true
          title: "Update to latest controller version"
